# Generated by Django 2.0.3 on 2020-09-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_user', models.CharField(max_length=64)),
                ('for_user', models.CharField(max_length=64)),
                ('is_view', models.BooleanField(default=False)),
            ],
        ),
    ]
