# Generated by Django 3.1.1 on 2020-09-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Disease', models.CharField(max_length=64)),
                ('Precaution_1', models.CharField(blank=True, max_length=64)),
                ('Precaution_2', models.CharField(blank=True, max_length=64)),
                ('Precaution_3', models.CharField(blank=True, max_length=64)),
                ('Precaution_4', models.CharField(blank=True, max_length=64)),
            ],
        ),
    ]
