# Generated by Django 3.1.1 on 2020-10-25 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0002_auto_20201024_0643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='meessage_doctor',
            new_name='message_doctor',
        ),
        migrations.AlterField(
            model_name='meeting_details',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='patients_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_intro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='doctor_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='')),
                ('specialization', models.TextField(max_length=64)),
                ('payment_details', models.TextField()),
                ('NMC_ID', models.IntegerField()),
                ('feesdetail', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_intro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='hospital',
            name='doctors',
            field=models.ManyToManyField(blank=True, related_name='hospitals', to='myapp.doctor_profile'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='doctors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.doctor_profile'),
        ),
        migrations.DeleteModel(
            name='doctor',
        ),
    ]
