# Generated by Django 3.1.1 on 2020-10-27 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20201025_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_profile',
            name='profile_pic',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=1)),
                ('StartTime', models.TimeField(default=10)),
                ('BreakStartTime', models.TimeField(default=1)),
                ('BreakEndTime', models.TimeField(default=2)),
                ('EndTime', models.TimeField(default=5)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='myapp.doctor_profile')),
            ],
        ),
    ]
