# Generated by Django 3.1.1 on 2020-10-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='user_type',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
