# Generated by Django 3.1.1 on 2020-10-27 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20201027_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_profile',
            name='NMC_ID',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor_profile',
            name='feesdetail',
            field=models.IntegerField(blank=True, default=500),
        ),
        migrations.AlterField(
            model_name='doctor_profile',
            name='payment_details',
            field=models.TextField(blank=True, max_length=64),
        ),
    ]
