# Generated by Django 3.1.1 on 2020-10-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20201007_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='user_type',
            field=models.TextField(blank=True, default='patients', max_length=50),
        ),
    ]
