# Generated by Django 3.1.1 on 2020-10-07 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20201007_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='user_type',
            field=models.CharField(choices=[(1, 'Doctor'), (2, 'Patients')], default=2, max_length=10),
        ),
    ]
