# Generated by Django 3.1.1 on 2020-10-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20201007_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='user_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Doctor'), (2, 'Patients')], null=True),
        ),
    ]
