# Generated by Django 3.1.1 on 2020-11-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20201029_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients_profile',
            name='profile_pic',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
