# Generated by Django 3.1.1 on 2020-10-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20201007_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='hospital_id',
        ),
        migrations.AddField(
            model_name='hospital',
            name='doctors',
            field=models.ManyToManyField(blank=True, related_name='hospitaldoctor', to='myapp.doctor'),
        ),
    ]
