# Generated by Django 3.1.1 on 2020-11-04 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20201103_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting_details',
            name='receipt',
            field=models.ImageField(upload_to='receipt'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='patients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.patients_profile'),
        ),
    ]
