# Generated by Django 3.1.1 on 2020-11-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20201110_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_profile',
            name='wallet',
            field=models.IntegerField(blank=True, default=1000, null=True),
        ),
        migrations.AddField(
            model_name='patients_profile',
            name='wallet',
            field=models.IntegerField(blank=True, default=1000, null=True),
        ),
    ]
