# Generated by Django 3.1.1 on 2020-11-18 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_auto_20201111_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='doctors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting', to='myapp.doctor_profile'),
        ),
    ]
