# Generated by Django 3.1.1 on 2020-11-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_monitoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='picture',
            field=models.ImageField(default='hospital.jpg', upload_to='hospital'),
        ),
    ]
