# Generated by Django 3.1.1 on 2020-11-30 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_hospital_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting_details',
            name='receipt',
        ),
    ]
